services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - "5672:5672"     # MassTransit/RabbitMQ
            - "15672:15672"   # RabbitMQ web UI (http://localhost:15672)
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest

    postgres:
        image: postgres:16
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: appuser
            POSTGRES_PASSWORD: appsecret
            POSTGRES_DB: messagesdb
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data


    message-api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: message-api
        ports:
            - "8888:8888"
        # environment:
        #   - ASPNETCORE_URLS=http://+:8888
        #   - DOTNET_ENVIRONMENT=Development
        depends_on:
            - rabbitmq
            - postgres

volumes:
    pgdata: